[default]
app_name = "prospector"
database_url = "sqlite:///default.db"
normal_model = "gemini-2.5-flash"
reasoning_model = "gemini-2.5-pro"
temperature = 0.0

[default.logging]
log_level = "INFO"
log_format = "%(asctime)s | %(levelname)s | %(message)s"
